"""Markdown + JSON report renderer for pkgfence lookup mode."""
import datetime
import json


def _frontmatter(lookup_id: str) -> str:
    ts = datetime.datetime.now(datetime.timezone.utc).isoformat()
    return f"---\nlookup_id: {lookup_id}\ntimestamp: \"{ts}\"\n---\n\n"


def render_lookup_markdown(parsed: dict, advisory: dict, web: dict | None,
                           elapsed: float, consulted: list[str]) -> str:
    lid = parsed["value"]
    out = [_frontmatter(lid)]
    out.append(f"# Lookup: {lid}\n")
    out.append("## Advisory Data\n")

    if not advisory:
        out.append(f"_No advisory data found for {lid}._\n")
    else:
        for source, data in advisory.items():
            if data is None:
                continue
            out.append(f"### {source.upper()}\n")
            if isinstance(data, dict):
                for k, v in data.items():
                    if v is not None:
                        out.append(f"- **{k}:** {json.dumps(v, default=str)}")
                out.append("")
            elif isinstance(data, bool):
                out.append(f"- **Actively exploited:** {data}\n")
            else:
                out.append(f"- {data}\n")

    if web and (web.get("abstract") or web.get("related_topics")):
        out.append("## Web Search\n")
        if web.get("abstract"):
            out.append(f"- **Abstract:** {web['abstract']}")
            if web.get("abstract_url"):
                out.append(f"  [{web['abstract_url']}]({web['abstract_url']})")
            out.append("")
        if web.get("related_topics"):
            out.append("- **Related:**")
            for t in web["related_topics"]:
                url = t.get("url", "")
                if url:
                    out.append(f"  - [{t['text']}]({url})")
                else:
                    out.append(f"  - {t['text']}")
            out.append("")

    out.append(
        f"---\n*Generated by pkgfence v0.4.0 | Lookup completed in "
        f"{elapsed:.1f}s | Sources: {', '.join(consulted)}*"
    )
    return "\n".join(out)


def render_lookup_json(parsed: dict, advisory: dict, web: dict | None,
                       elapsed: float, consulted: list[str]) -> str:
    return json.dumps({
        "lookup_id": parsed["value"],
        "type": parsed["type"],
        "advisory": advisory,
        "web_search": web,
        "elapsed_seconds": round(elapsed, 2),
        "sources_consulted": consulted,
    }, indent=2, default=str)
